In [31]:
dset = r"C:\Users\Purushotham\Desktop\deloitte\machinelearning\datasets\housing.csv"

In [32]:
import pandas as pd
import matplotlib.pyplot as plt

In [33]:
df = pd.read_csv(dset)

In [34]:
df.head()

0.00632  18.00  2.310  0  0.5380  6.5750  65.20  4.0900  1  296.0  15.30  \
0  0.02731    0.0   7.07  0   0.469   6.421   78.9  4.9671  2  242.0   17.8   
1  0.02729    0.0   7.07  0   0.469   7.185   61.1  4.9671  2  242.0   17.8   
2  0.03237    0.0   2.18  0   0.458   6.998   45.8  6.0622  3  222.0   18.7   
3  0.06905    0.0   2.18  0   0.458   7.147   54.2  6.0622  3  222.0   18.7   
4  0.02985    0.0   2.18  0   0.458   6.430   58.7  6.0622  3  222.0   18.7   

   396.90  4.98  24.00  
0  396.90  9.14   21.6  
1  392.83  4.03   34.7  
2  394.63  2.94   33.4  
3  396.90  5.33   36.2  
4  394.12  5.21   28.7

In [35]:
df.shape

(505, 14)

In [37]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedKFold
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge

In [38]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [53]:
# model = Lasso(alpha = 1)
model = Ridge(alpha = 1)
model.fit(X, y)

Ridge(alpha=1)

In [40]:
cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)

In [41]:
score = cross_val_score(model, X, y, cv=cv, scoring='neg_mean_squared_error')

In [42]:
from sklearn import metrics
metrics.SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_wei

In [43]:
score

array([-21.14819423, -22.78815144, -17.60043104, -38.5687517 ,
        -9.12453305, -21.74431142, -31.73342959, -15.53904389,
       -42.6475397 , -21.98001983, -26.49715006, -18.48413341,
       -39.40109463, -19.40371543, -20.76290708, -21.08363458,
       -19.54742053, -28.7945072 , -21.96158834, -20.4534505 ,
       -16.81558052, -28.59748352, -21.23650982, -16.42811741,
       -24.12094285, -17.67223192, -19.19538939, -31.41940373,
       -36.06624826, -27.26125016])

In [44]:
len(score)

30

In [45]:
from numpy import mean, std, absolute

In [46]:
score = absolute(score)

In [47]:
score

array([21.14819423, 22.78815144, 17.60043104, 38.5687517 ,  9.12453305,
       21.74431142, 31.73342959, 15.53904389, 42.6475397 , 21.98001983,
       26.49715006, 18.48413341, 39.40109463, 19.40371543, 20.76290708,
       21.08363458, 19.54742053, 28.7945072 , 21.96158834, 20.4534505 ,
       16.81558052, 28.59748352, 21.23650982, 16.42811741, 24.12094285,
       17.67223192, 19.19538939, 31.41940373, 36.06624826, 27.26125016])

In [48]:
# Mean - MAE
mean(score)

23.93590550782699

In [49]:
# STD DEV 
std(score)

7.654854091893565

### How to predict future/ new values

In [50]:
df.iloc[1]

0.00632      0.02729
18.00        0.00000
2.310        7.07000
0            0.00000
0.5380       0.46900
6.5750       7.18500
65.20       61.10000
4.0900       4.96710
1            2.00000
296.0      242.00000
15.30       17.80000
396.90     392.83000
4.98         4.03000
24.00       34.70000
Name: 1, dtype: float64

In [51]:
import random
data = [random.random() for i in range(13)]
data

[0.1946526309844976,
 0.6848138157077444,
 0.27777116867332663,
 0.7967329131403875,
 0.09345907490626482,
 0.1802413944533825,
 0.7699613952939742,
 0.7541505907018483,
 0.8184646429547046,
 0.12237810976197594,
 0.018866765692704845,
 0.7327137532479782,
 0.6314185344560411]

In [54]:
model.predict([data])

C:\Users\Purushotham\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\base.py:442: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  "X does not have valid feature names, but"


array([32.38174425])