In [1]:
import tensorflow as tf
tf.__version__

'2.6.0'

In [2]:
import pandas as pd

### Initialization of Tensors

In [3]:
x = 10
print(x)

10


In [4]:
type(x)

int

In [6]:
x = tf.constant(10)
x

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [9]:
x = tf.constant(10, shape=(2, 2), dtype=tf.float32)
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[10., 10.],
       [10., 10.]], dtype=float32)>

In [11]:
x = tf.constant([10, 20, 30, 40], shape=(2, 2), dtype=tf.float32)
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[10., 20.],
       [30., 40.]], dtype=float32)>

In [13]:
x = tf.constant([10, 20, 30], shape=(1, 3), dtype=tf.float32)
x

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[10., 20., 30.]], dtype=float32)>

In [14]:
x = tf.constant([10, 20, 30], shape=(3, 1), dtype=tf.float32)
x

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[10.],
       [20.],
       [30.]], dtype=float32)>

In [17]:
x = tf.constant([[10, 20, 30], [40, 50, 60]], shape=(3, 2), dtype=tf.float32)
x

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10., 20.],
       [30., 40.],
       [50., 60.]], dtype=float32)>

In [18]:
tf.ones((3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [19]:
tf.zeros((3, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [20]:
tf.eye(3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [21]:
tf.range(10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [22]:
tf.range(start=1, limit=20, delta=3)

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([ 1,  4,  7, 10, 13, 16, 19])>

In [23]:
tf.random.uniform((3,3), minval=0, maxval=3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[2.1445463 , 1.6314118 , 2.983385  ],
       [0.32513094, 0.62303996, 1.9193902 ],
       [0.02447176, 1.7481887 , 0.8806057 ]], dtype=float32)>

In [24]:
tf.random.normal((5,5), mean=0, stddev=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.2695155 ,  0.73712915,  0.6797922 ,  1.3061135 , -0.0114889 ],
       [-0.34328064,  0.44189176, -0.3730192 , -1.8926729 ,  0.88534576],
       [ 1.8816733 ,  1.2419357 ,  2.2958446 , -0.98378634,  0.2976266 ],
       [-1.0014094 , -0.16461368, -0.8658073 , -1.7212021 , -0.07271829],
       [ 1.6246855 ,  1.0381364 ,  0.20539601,  0.75268346, -0.6649557 ]],
      dtype=float32)>

In [25]:
x = tf.range(10)

In [26]:
x

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [27]:
tf.cast(x, dtype=tf.float32)

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

### Mathematical Operations

In [28]:
x = tf.constant(10)
y = tf.constant(20)

In [29]:
type(x)

tensorflow.python.framework.ops.EagerTensor

In [30]:
x + y

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [31]:
tf.add(x,y)

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [32]:
tf.subtract(x,y)

<tf.Tensor: shape=(), dtype=int32, numpy=-10>

In [33]:
tf.multiply(x, y)

<tf.Tensor: shape=(), dtype=int32, numpy=200>

In [34]:
tf.divide(x, y)

<tf.Tensor: shape=(), dtype=float64, numpy=0.5>

In [42]:
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))

In [44]:
tf.matmul(x, y)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 1.9041513 , -0.5205671 ,  0.9650185 , -2.5438151 ],
       [ 1.9232719 ,  1.085324  ,  0.47293463, -2.6411028 ]],
      dtype=float32)>

In [45]:
x @ y

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 1.9041513 , -0.5205671 ,  0.9650185 , -2.5438151 ],
       [ 1.9232719 ,  1.085324  ,  0.47293463, -2.6411028 ]],
      dtype=float32)>

### Index

In [46]:
x = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [47]:
x[2]

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [48]:
x[2:5]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 4, 5])>

In [49]:
x[:]

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])>

In [50]:
x[2:]

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([ 3,  4,  5,  6,  7,  8,  9, 10])>

In [51]:
x[:6]

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6])>

In [52]:
x[::2]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

In [53]:
tf.gather(x, [0, 3, 7])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 8])>

In [56]:
x = tf.constant([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [57]:
x[0,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [58]:
x[0:2, :]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [59]:
x[0, : 1:2]

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([1])>

In [60]:
x[ : 0:2]

<tf.Tensor: shape=(0, 3), dtype=int32, numpy=array([], shape=(0, 3), dtype=int32)>

In [64]:
x[0:2, 0:2]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5]])>

### Reshaping

In [74]:
x = tf.range(10)

In [75]:
x

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [76]:
tf.reshape(x, (2, 5))

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])>

### Sessions

In [10]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
x = tf.constant(2)
y = tf.constant(3)

add_op = tf.add(x, y, name='Add')
mul_op = tf.multiply(x, y, name='Multiply')
pow_op = tf.pow(add_op, mul_op, name='Power')
some_op = tf.divide(pow_op, add_op, name='Some')

print(add_op, mul_op, pow_op, some_op)

with tf.compat.v1.Session() as session:
    pow_out, some_out = session.run([pow_op, some_op])
    
print(add_op, mul_op, pow_out, some_out)

Tensor("Add_5:0", shape=(), dtype=int32) Tensor("Multiply_5:0", shape=(), dtype=int32) Tensor("Power_5:0", shape=(), dtype=int32) Tensor("Some_4:0", shape=(), dtype=float64)
Tensor("Add_5:0", shape=(), dtype=int32) Tensor("Multiply_5:0", shape=(), dtype=int32) 15625 3125.0


In [11]:
colors = ["red", "green", "blue"]

In [12]:
r, g, b = colors
print(r, g, b)

red green blue


In [13]:
colors = ["red", "green", "blue", "yellow", "pink"]
r, g, b = colors
print(r, g, b)


ValueError: too many values to unpack (expected 3)

In [14]:
r, g, b, *x = colors
print(r, g, b, x)

red green blue ['yellow', 'pink']


In [16]:
colors

['red', 'green', 'blue', 'yellow', 'pink']

In [17]:
_, *x = colors

In [18]:
x


['green', 'blue', 'yellow', 'pink']

In [20]:
_, *x = colors

In [21]:
_

'red'

In [23]:
T1 = ("red", "green", "blue")
T2 = (1, 2, 3, 4)
dict(zip(T1, T2))

{'red': 1, 'green': 2, 'blue': 3}

In [24]:
D = {'red': 1, 'green': 2, 'blue': 3}
D.items()

dict_items([('red', 1), ('green', 2), ('blue', 3)])

In [25]:
T1 = ("red", "green", "blue")
T2 = (1, 2, 3, 4)
list(zip(T1, T2))

[('red', 1), ('green', 2), ('blue', 3)]

In [26]:
LT = [('red', 1), ('green', 2), ('blue', 3)]
list(zip(*LT))

[('red', 'green', 'blue'), (1, 2, 3)]

In [29]:
import numpy as np
tf.compat.v1.disable_eager_execution()
x = tf.compat.v1.placeholder(tf.float32, shape=(2,2))
y = tf.matmul(x, x)

with tf.compat.v1.Session() as session:
    data = np.random.rand(2, 2)
    result = session.run(y, feed_dict={x: data})
    print(data)
    print(result)

[[0.07717548 0.98123449]
 [0.11675271 0.72391886]]
[[0.12051784 0.78606135]
 [0.09352994 0.6386203 ]]


### Keras

In [39]:

from keras.models import Sequential

In [ ]:
%pip install keras

In [32]:
from keras.layers import Dense, Activation, Dropout

In [33]:
num_classes = 3

In [36]:
model = Sequential()
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(num_classes, activation='softmax'))

### Linear Regression using Tensor Flow

In [65]:
import tensorflow as tf
import numpy as np
tf.compat.v1.enable_eager_execution()

ValueError: tf.enable_eager_execution must be called at program startup.

In [41]:
X = np.array([3.3,4.4,5.5,6.71,6.93,4.168,9.779,6.182,7.59,2.167,
              7.042,10.791,5.313,7.997,5.654,9.27,3.1])
Y = np.array([1.7,2.76,2.09,3.19,1.694,1.573,3.366,2.596,2.53,1.221,
              2.827,3.465,1.65,2.904,2.42,2.94,1.3])

In [42]:
#  Weight and bias, initialized randomly
W = tf.Variable(np.random.randn(), name='weight')
b = tf.Variable(np.random.randn(), name='bias')

In [43]:
def linear_regression(x):
    return W*x + b

In [44]:
def mean_square(y_pred, y_true):
    return tf.reduce_mean(tf.square(y_pred - y_true))

In [45]:
linear_regression(X)

<tf.Tensor 'add_6:0' shape=(17,) dtype=float32>

In [58]:
optimizer = tf.optimizers.SGD(0.1)

In [61]:
def run_optimization():
    
    with tf.GradientTape() as g:
        pred = linear_regression(X)
        loss = mean_square(pred, Y)
    
    gradients = g.gradient(loss, [W, b])
    print(gradients)
    
    optimizer.apply_gradients(zip(gradients, [W, b]))
    

In [62]:
run_optimization()

[<tf.Tensor 'gradient_tape/mul_5/Reshape:0' shape=() dtype=float32>, <tf.Tensor 'gradient_tape/add_11/Reshape:0' shape=() dtype=float32>]


In [63]:
for step in range(1, 1000):
    run_optimization()
    
    if step % 50 == 0:
        pred = linear_regression(X)
        loss = mean_square(pred, Y)
        print("step: {}, loss: {}, W: {}, b: {}".format(step, loss, W.numpy(), b.numpy()))

[<tf.Tensor 'gradient_tape/mul_6/Reshape:0' shape=() dtype=float32>, <tf.Tensor 'gradient_tape/add_12/Reshape:0' shape=() dtype=float32>]
[<tf.Tensor 'gradient_tape/mul_7/Reshape:0' shape=() dtype=float32>, <tf.Tensor 'gradient_tape/add_13/Reshape:0' shape=() dtype=float32>]
[<tf.Tensor 'gradient_tape/mul_8/Reshape:0' shape=() dtype=float32>, <tf.Tensor 'gradient_tape/add_14/Reshape:0' shape=() dtype=float32>]
[<tf.Tensor 'gradient_tape/mul_9/Reshape:0' shape=() dtype=float32>, <tf.Tensor 'gradient_tape/add_15/Reshape:0' shape=() dtype=float32>]
[<tf.Tensor 'gradient_tape/mul_10/Reshape:0' shape=() dtype=float32>, <tf.Tensor 'gradient_tape/add_16/Reshape:0' shape=() dtype=float32>]
[<tf.Tensor 'gradient_tape/mul_11/Reshape:0' shape=() dtype=float32>, <tf.Tensor 'gradient_tape/add_17/Reshape:0' shape=() dtype=float32>]
[<tf.Tensor 'gradient_tape/mul_12/Reshape:0' shape=() dtype=float32>, <tf.Tensor 'gradient_tape/add_18/Reshape:0' shape=() dtype=float32>]
[<tf.Tensor 'gradient_tape/mul_

NotImplementedError: numpy() is only available when eager execution is enabled.